### PR TITLE
Ability to swap scrolling runes 

### PR DESCRIPTION
**Pull request by d-ank**
#245 fixes this issue with windows consoles by adding option to switch the scroll runes on a text widget.
The option `text.ScrollRunes` accepts two rune parameters, up and down, the default runes are the same `⇧` and `⇩`.

An example of this which will draw correct scroll runes on windows
`text.New(text.RollContent(), text.WrapAtWords(), text.ScrollRunes('▲', '▼'))`

### CODE REVIEW

**Comment by d-ank** [comment]
@googlebot I signed it!

**Review by mum4k — CHANGES_REQUESTED** [review]
Looks spot on, thank you for the contribution.

Would you be also willing to add test coverage for the new options? It should be as simple as copying and slightly modifying some of the existing test cases here:

https://github.com/mum4k/termdash/blob/master/widgets/text/text_test.go

You can try searching for "scroll marker" to find test cases that exercise behaviors resulting in the scroll arrows being drawn. We can add two test cases, one that draws the bottom marker and one that draws the top one.

**Comment by d-ank** [comment]
Sorry I won't be able to add the test coverage till the weekend.

**Comment by mum4k** [comment]
No rush @d-ank, please take your time.

**Comment by mum4k** [comment]
Hi @d-ank, just checking in, are you still interested in adding the tests. Or would you prefer if we merge it in as is and I add the test coverage separately?

**Comment by mum4k** [comment]
Thanks again @d-ank for the contribution, I will merge this in and add the tests.

**Pull request merged**
